<?php
namespace App\Services;

use App\Models\Connection;
use App\Services\BaseService;
use App\Models\Deploy;
use App\Models\Change;

use Illuminate\Support\Facades\DB;

use Connect;

class SyncService extends BaseService
{
    protected $deploy, $source, $dest;

    public function generateSql(array $changes_list) {
        $changes = Change::whereIn('id', $changes_list)->get();

        $sql = '
            /* MySQL Script generated by DifferDB */
        ';

        $sql .= "\n";

        foreach($changes as $change) {
            $sql .= $change->sql;
        }

        return $sql;
    }
    public function executeMysql($sql, Connection $connection, $databases) {
        array_unshift($databases, $connection->database_name);

        $results = [];

        foreach($databases as $database_name) {
            $connection_array = [
                'host' => $connection->host,
                'username' => $connection->username,
                'password' => $connection->password,
                'database_name' => $database_name
            ];
            $connect = Connect::connect('db_two', $connection_array);
            if($connect === true) {
                try {
                    DB::unprepared($sql);
                    $results[$database_name]['success'] = true;
                    $results[$database_name]['message'] = 'Synchronization successful!';
                } catch(\Exception $e) {
                    $results[$database_name]['success'] = false;
                    $results[$database_name]['message'] = $e->getMessage();
                }
            } else {
                $results[$database_name]['success'] = false;
                $results[$database_name]['message'] = $connect;
            }
        }

        return $results;

    }
}